# Basic set up for two package managers

version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      # Allow updates for Lodash
      - dependency-name: "lodash"
      # Allow updates for React and any packages starting "react"
      - dependency-name: "react*"
    # Add assignees
    assignees:
      - "wvanheemstra"
    commit-message:
      # Prefix all commit messages with "npm: "
      prefix: "npm"
    ignore:
      - dependency-name: "express"
        # For Express, ignore all updates for version 4 and 5
        versions: ["4.x", "5.x"]
    # Specify labels for npm pull requests
    labels:
      - "npm"
      - "dependencies"        
